name: beacon_broadcast
description: A Flutter plugin for turning your device into a beacon. Plugin uses AltBeacon library for Android and
  CoreLocation for iOS.
version: 0.2.3
homepage: https://github.com/pszklarska/beacon_broadcast

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.15.5
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: pl.pszklarska.beaconbroadcast
        pluginClass: BeaconBroadcastPlugin
      ios:
        pluginClass: BeaconBroadcastPlugin